
name: 'Fouler'
description: 'A Github Action to detect Foul words in a PR or an Issue created and optionally close it'
author: 'Prateek93a'
inputs:
  token:              # change this
    description: 'Your Github Token'
    required: true
  close_permission:
    description: 'Allow the Action to close the PR or the Issue. Write true or false'
    required: false
    default: false
  message:
    description: 'Message that gets displayed when foul words are detected'
    required: false
    default: 'Use of foul words detected'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'mic-off'  
  color: 'red'